name: Build LaTeX document
on:
  create:
    branches: [master]
    tags:
      - '*'
jobs:
  build_latex:
    name: Compile Latex Files
    runs-on: ${{matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile Latex document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
          latexmk_shell_escape: true
          args: -pdf -cd --output-directory=../out

      - name: Show folder entries
        run: ls && ls out

      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: out/main.pdf
  
  release_pdf:
    name: Release PDF
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: main.pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "main.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
